# Generated by Django 2.0.6 on 2018-08-18 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
