# Generated by Django 2.0.6 on 2018-07-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20180721_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='items',
            new_name='item',
        ),
    ]
