# Generated by Django 2.0.6 on 2018-08-18 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Base',
            new_name='Home',
        ),
    ]
